name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Create deployment package
        run: |
          mkdir deploy
          shopt -s extglob
          cp -r !(deploy) deploy/
          tar -czf deploy.tar.gz deploy
          rm -rf deploy

      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no deploy.tar.gz ec2-user@ec2-100-25-98-47.compute-1.amazonaws.com:/home/ec2-user/

      - name: Extract deployment package on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@ec2-100-25-98-47.compute-1.amazonaws.com 'mkdir -p /home/ec2-user/pokedex && tar -xzf /home/ec2-user/deploy.tar.gz -C /home/ec2-user/pokedex && rm /home/ec2-user/deploy.tar.gz'

      - name: Install dependencies on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@ec2-100-25-98-47.compute-1.amazonaws.com 'sudo yum install -y libcrypt'

      - name: Run Docker Compose on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@ec2-100-25-98-47.compute-1.amazonaws.com 'cd /home/ec2-user/pokedex && docker-compose up --build -d'
